DROP TABLE IF EXISTS bonus;

CREATE TABLE bonus
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    BONUS_NAME VARCHAR(250) NOT NULL,
    BONUS_TYPE VARCHAR(250) NOT NULL,
    START_TIME TIMESTAMP  DEFAULT NULL,
    END_TIME   TIMESTAMP  DEFAULT NULL
);
